# Generated by Django 4.1.6 on 2023-05-03 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PlayLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("player_name", models.CharField(max_length=1024, null=True)),
                ("end_time", models.CharField(max_length=1024, null=True)),
                ("duration", models.CharField(max_length=1024, null=True)),
                ("ad_copy_name", models.CharField(max_length=1024, null=True)),
                ("Number_of_Screens", models.CharField(max_length=1024, null=True)),
                ("Campaign_Name", models.CharField(max_length=1024, null=True)),
                ("Frame_Name", models.CharField(max_length=1024, null=True)),
                ("Display_Unit_Name", models.CharField(max_length=1024, null=True)),
                ("Impressions", models.CharField(max_length=1024, null=True)),
                ("Interactions", models.CharField(max_length=1024, null=True)),
                ("Extra_Data", models.CharField(max_length=1024, null=True)),
                ("variable", models.CharField(max_length=1024, null=True)),
            ],
        ),
    ]
