# Generated by Django 4.2.1 on 2023-06-06 03:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Playlog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playlog',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='playlog',
            name='Campaign_Name',
            field=models.CharField(db_index=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='playlog',
            name='end_time',
            field=models.CharField(db_index=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='playlog',
            name='player_name',
            field=models.CharField(db_index=True, max_length=1024, null=True),
        ),
    ]
