# Generated by Django 4.2.1 on 2023-06-06 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Playlog', '0003_campaign_remove_playlog_campaign_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, default=None, max_length=1024, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='playlog',
            name='player_name',
        ),
        migrations.AlterField(
            model_name='playlog',
            name='Impressions',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='playlog',
            name='Interactions',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='playlog',
            name='player',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='playlogs', to='Playlog.player'),
        ),
    ]
